version: '3.8'

services:
  postgres:
    container_name: social-linx-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: social-linx
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: social-linx-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
